# 应用服务 WEB 访问端口
server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-t4njraxo75r1e4jlevo.mysql.singapore.rds.aliyuncs.com:3306/javapub_test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: javapub_admin
    password: JavaPub666
  sql:
    init:
      schema-locations:

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.net.javapub.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来





